# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADName', models.CharField(max_length=200)),
                ('ADemail', models.CharField(max_length=70)),
                ('ADpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date_added', models.DateField()),
                ('date_tobe_completed', models.DateField()),
                ('final_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=200)),
                ('C_Phone_num', models.CharField(max_length=10)),
                ('C_Address', models.CharField(max_length=500)),
                ('C_email', models.CharField(max_length=70)),
                ('C_password', models.CharField(max_length=100)),
                ('C_rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='service_providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPName', models.CharField(max_length=200)),
                ('SPPhone_num', models.CharField(max_length=10)),
                ('SPAddress', models.CharField(max_length=500)),
                ('SPemail', models.CharField(max_length=70)),
                ('SPpassword', models.CharField(max_length=100)),
                ('SPrating', models.IntegerField(null=True)),
                ('service_offered', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='service_list',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booknow.service_providers'),
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booknow.service_list'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booknow.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booknow.service_providers'),
        ),
    ]
