# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='admin1',
        ),
    ]
